### ISSUE TITLE
Do u have a plan for supporting .net core?

### ISSUE THREAD

**Issue by fudiwei** [jpush/jpush-api-csharp-client#11]
As the title suggests.

**Comment by compass-yan** [comment]
from negut can get it,but it really work not good

**Comment by fudiwei** [comment]
@sesamefly Did u mean the nuget package named of 'cn.jpush.api.core'? I'm afraid it's an unofficial one.

**Comment by lhw5123** [comment]
[Jiguang.JPush](https://preview.nuget.org/packages/Jiguang.JPush/) is based on [.NET Standard 1.6](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.6.md). It's official one.

**Comment by fudiwei** [comment]
@lhw5123 thx, I will try. :+1:

**Comment by compass-yan** [comment]
@lhw5123  oh,oh ,it's greate message. thanks
