### ISSUE TITLE
如何给 iOS 平台的通知设置标题

### ISSUE THREAD

**Issue by wanqingrongruo** [jpush/jpush-api-csharp-client#14]
请问c#这边如何给 iOS 平台的通知设置标题/副标题,用 web 端可以,为何在 IosNotification类中没有找到相应的属性去设置,只能单纯的设置 alert显示消息内容.

**Comment by lhw5123** [comment]
iOS 的 `alert` 既可以传单纯的字符串，也可以传一个 Dictionary。
Dictionary 中可以设置标题，具体支持的字段可以查阅[官方文档](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html)。
