### ISSUE TITLE
在Windows XP系统下接口调用失败。

### ISSUE THREAD

**Issue by ajian55** [jpush/jpush-api-csharp-client#15]
出现问题的操作系统版本：Windows XP professional 版本2002 sp3 （测试了XP机器）

使用的jpush api版本：jpush-api-csharp-client-3.3.1

接口调用异常：The underlying connection was closed: An unexpected error occurred on a send。

调试发现是向https://api.jpush.cn/v3/push发送post请求时出现异常，我测试了其它的https的url，比如百度的https://www.baidu.com 不会报上述异常，网络大部分关于“The underlying connection was closed: An unexpected error occurred on a send” 或者 “C# HttpRequest基础连接已经关闭: 接收时发生意外错误” 的解决方案都试了一遍，均无法解决上述问题。

**Comment by lhw5123** [comment]
参考下这篇文章：http://blogs.perficient.com/microsoft/2016/04/tsl-1-2-and-net-support/

**Comment by ajian55** [comment]
意思就是说在XP下无解咯？ 因为XP是无法安装4.0以上.net框架的，也没有什么补丁包可用~

**Comment by lhw5123** [comment]
如果是用的 .NET 4.0，可以尝试加上这段代码：
```csharp
ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;
```
3.5 及以下就没办法了。

**Comment by ajian55** [comment]
我理解的参考文章里面的意思是：

> 如果是用的 .NET 4.0，可以尝试加上这段代码：
> ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;

但有个前提，就是操作系统已经安装了 .NET 4.5 (or above)的环境，只是我们的开发环境用的是4.0，那么在编译器里面找不到SecurityProtocolType.Tls12也没关系，因为我们可以使用上述代码代替。

但是，在XP系统下是无法安装 .NET 4.5 (or above)的环境的，所以这个方案是pass掉的，所以，没办法咯？

**Comment by lhw5123** [comment]
TLS 1.2 必须要 .NET 4.5，如果没有，那确实没办法了。

**Comment by ajian55** [comment]
今天把问题解决了。

http://blog.csdn.net/ajian55/article/details/77678237
