### ISSUE TITLE
我引用后运行后一直报错

### ISSUE THREAD

**Issue by jone78** [jpush/jpush-api-csharp-client#16]
#原来环境是vs2013，看到不支持c#6，就下载了vs2015，可是vs2015运行后一直报错，这是报错（未能加载文件或程序集“System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11“）。不过项目中我引用了System.Net.Http。这个demo我也运行不起来啊

**Comment by lhw5123** [comment]
看下是不是 `System.Net.Http` 依赖版本不对。

**Comment by jone78** [comment]
回家我再调试下

**Comment by compass-yan** [comment]
试下vs2017

**Comment by jone78** [comment]
OK 了
