### ISSUE TITLE
用官网C# sdk Demo，无响应

### ISSUE THREAD

**Issue by lfc555** [jpush/jpush-api-csharp-client#17]
上传不了图片.... 就是demo 里面的这句发送推送的请求
   var response =client.SendPushAsync(pushPayload).Result;
执行到这里就一直没有反应了,页面也卡住了
，但推送已发送成功，android已收到通知

**Comment by lfc555** [comment]
改成这样就可以，但后面又报异常，未将对应设置到实例之类的
var response =client.SendPushAsync(pushPayload);
反正就是获取不到 请求的结果 result

**Comment by lhw5123** [comment]
关于异步方法的使用可以参考下这个[链接](https://blogs.msdn.microsoft.com/jpsanders/2017/08/28/asp-net-do-not-use-task-result-in-main-context/)。
之后我加一下同步方法。

**Comment by lfc555** [comment]
```csharp
public string Get(int id) {
    string ret = "";

    // Start a task - calling an async function in this example
    Task<string> callTask = Task.Run(() => Utilities.CallHttp());
    // Wait for it to finish
    callTask.Wait();
    // Get the result
    ret = callTask.Result;

    return ret;
}
```
用这个可以。
