### ISSUE TITLE
初始化Notification，报null。

### ISSUE THREAD

**Issue by xyfy** [jpush/jpush-api-csharp-client#18]
`  var x = new Notification
                {
                    Alert = systemNotify.Alert,
                    Android =
                    {
                        Title = ""
                    }
                }`
如果不要Android属性，则没有报null异常，但是如果是加上下面Android的这个属性就会报异常。
sdk版本号1.0.7

**Comment by lhw5123** [comment]
我这里用下面这样的写法，没有出现问题，你参考下：
```csharp
PushPayload pushPayload = new PushPayload()
{
    Platform = "android",
    Audience = "all",
    Notification = new Notification()
    {
        Alert = "hello jpush",
        Android = new Android() {
            Title = "title"
        }
    }
};
```
