### ISSUE TITLE
The Annotations is necessary

### ISSUE THREAD

**Issue by chahugai** [jpush/jpush-api-csharp-client#8]
The Annotations is necessary. Also in the DLL.

**Comment by fendouai** [comment]
The project has a README(https://github.com/jpush/jpush-api-csharp-client/blob/master/README.md) and many examples(https://github.com/jpush/jpush-api-csharp-client/tree/master/cn.jpush.api.example ).Thank you for your advice,I will consider to add more annotations to the project.
