### ISSUE TITLE
ISO推送没有声音

### ISSUE THREAD

**Issue by mkxzy** [jpush/jpush-api-csharp-client#9]
notification.IosNotification = new IosNotification()
                .AddExtra("Type", "Follow")
                .AddExtra("Param", paraJson)
                .setSound("default")  //无效，通过日志调试，发现sound始终为空
                .setAlert(entity.Summary);

**Comment by fendouai** [comment]
你好，可以放一下推送的 json 吗？我刚才测试有声音，sound 也有对应的值。
